### ISSUE TITLE
Every adverb has different modifiers, could it lead to the numerous parameter to train than traditional methods?

### ISSUE THREAD

**Issue by alice-cool** [hazeld/action-modifiers#2]

**Comment by hazeld** [comment]
Each adverb is representated as one action modifier which is shared across actions. The action modifiers are 300x300D matrices, therefore there is one such matrix per adverb. So it could be larger than traditional methods depending on which method's you're refering to, although it is possible to reduce the dimensions of the embedding space and therefore the action modifiers.

**Comment by alice-cool** [comment]
Thanks for your reply.&nbsp; Thank you all the time.&nbsp;



---Original---

**Comment by alice-cool** [comment]
I look at your code carefully. And it is so nice. I find except the action modifiers are multiple, the other matrix is unique, that is to say the model only choose different action modifiers for different word composition for unseen word composition, and other module's parameters are shared to train. Also your action modifiers also can be shared when inferencing unseen word composition. 
Thanks for your creative thinking about image-adverb retrieval

**Comment by hazeld** [comment]
Thanks :smiley:
