### ISSUE TITLE
How did you obtain clean captions for youtube videos

### ISSUE THREAD

**Issue by thechargedneutron** [hazeld/action-modifiers#4]
Thank you for the good work!
How did you obtain clean (un-punctuated) captions for the videos from HowTo100M data? The captions given in the HowTo100M data when concatenated does not always makes a coherent sentence in many cases. For example, a sample from your subtitles : 
>[ Evening Stroll music ] Greetings my lovelies Hi. It'S Emmy, Welcome back to another'Emmy, Eats !' Today I'll be eating Belgium. So this beautiful package and my actual very first taste of Belgium was sent to me by long time. Viewer, Céline, Céline. Thank you. So much for sending me this package, I've been anticipating Belgium for a long time, And finally, I get my very first taste. So Céline has been watching my videos for a long time now

 and a sample from HowTo100M captions: 
>start,end,text
0.0,6.0,evening stroll music
6.14,8.92,greetings lovelies hi emmy 'emmy eats '
9.02,10.72,eating belgium
10.84,16.78,beautiful package actual taste belgium sent long time céline
16.9,19.58,céline sending package
19.74,24.2,anticipating belgium long time finally get taste
24.3,26.78,céline watching videos long time
26.9,30.64,way iived japan started eating country videos
30.78,33.58,céline sticking years

The punctuator tool ([here](http://bark.phon.ioc.ee/punctuator)) can only punctuate and cannot add coherence to the text as per my understanding. 

Can you please elaborate how did you obtain clean captions from the youtube videos? Did you use some external tool and/or a different version of HowTo100M captions?

**Comment by hazeld** [comment]
Hi,

Thanks for your interest in the work.

We don't use the captions provided alongside the HowTo100M dataset, we use the raw subtitles (i.e. the transcription of the audio) from the YouTube video. These can be obtained with youtube-dl (see here: https://github.com/ytdl-org/youtube-dl#subtitle-options). Due to the way YouTube displays the subtitles these often contain duplicates of the same phrase so we remove these and the timestamps to collapse it into one text for punctuation.

**Comment by thechargedneutron** [comment]
> we remove these and the timestamps to collapse it into one text for punctuation

Does this mean you remove the duplicates manually? Or is there some automated way to remove the duplicate? I can imagine matching strings and then removing the duplicates but that may not be accurate.

Additionally, the paper mentions that "In total, we have 24,558 videos in training and 1,280 videos in the test set.". This repo contains list of verbs that you obtain after the process described in the paper. Can you also release the list of these 24,558 and 1,280 videos? The given list in `train.csv` contains only processed action-adverb pairs, i.e. 5476 rows.

**Comment by hazeld** [comment]
We did this automatically by removing any special characters and additional whitespace and lowercasing everything then comparing the strings. The duplicates are just from the way YouTube displays subtitles as the previous subtitle is often displayed above the current one. This means the duplicates tend to be exact matches.

For the videos it should just be all the videos in it should just be all the videos in the punctuated_subs tar with a task number which is also in `data/tasks.csv`. The subtitles are grouped into directories which correspond to the task number.

**Comment by thechargedneutron** [comment]
Thanks for the help! Both my doubts are resolved now.
